### ISSUE TITLE
wall check for aimbot not working

### ISSUE THREAD

**Issue by koassount** [sirk1x/ResurrectedEternal#1]
no idea if thats the reason, but the aimbot straight up targets enemies through walls, even with AimSpottedOnly in the config
also im guessing the reason spottedbymask is used for glow/trigger is to save resources? kinda weird when you have raytracing, no?
[wallcheck?](https://github.com/sirk1x/ResurrectedEternalLite/blob/55eaf7f54d15d5fbc659ab17311688b398401d11/Skills/GamePlaySkillMods/SkillModAim.cs#L155)

[2 break statements (only in the main source, not in lite)](https://github.com/sirk1x/ResurrectedEternal/blob/285c7f09b8c21af31f04895efd2395593a4be7d5/Skills/GamePlaySkillMods/SkillModAim.cs#L513)

**Comment by sirk1x** [comment]
Yeah, i changed the config a bit to "legit gameplay" since the lite version doesn't use much resources and spottedbymask compliments that. Aimbot is currently set to 0 to [ignore walls](https://github.com/sirk1x/ResurrectedEternalLite/blob/55eaf7f54d15d5fbc659ab17311688b398401d11/Skills/GamePlaySkillMods/SkillModAim.cs#L483).

There are 2 configurations for the visible check 

- [Aimbot](https://github.com/sirk1x/ResurrectedEternalLite/blob/55eaf7f54d15d5fbc659ab17311688b398401d11/Configs/GamePlayConfig/AimbotConfig.cs#L28)
- [Neon](https://github.com/sirk1x/ResurrectedEternalLite/blob/55eaf7f54d15d5fbc659ab17311688b398401d11/Configs/GamePlayConfig/NeonConfig.cs#L22)

But if i remember correctly, there is a bug if you turn it completely off. I will check that later. Also im planning to drop a refactored version later on since the code has too many namespaces.

If you download the [Maps](https://www.resurrected.cc/maps.zip) from the project page and place them in the same folder, the hack should automatically check if that map is available and enable perfect raytrace for everything.

Dunno what happened with the break statements :^)

i hope that answers your question

**Comment by sirk1x** [comment]
[3b36293](https://github.com/sirk1x/ResurrectedEternalLite/commit/3b362934d6bc55cfc9d20ef8a8066b84a59bb497) should be fixed now, added simple booleans since the VisualCheck is too confusing for config entries
